blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://discuss.elastic.co/c/search/
    about: Please ask and answer questions here.
  - name: Security Vulnerability
    url: https://github.com/elastic/.github/blob/main/SECURITY.md
    about: DO NOT file issues related to security. Instead, please follow our security policy here.
